source('/data/jux/BBL/projects/ballerDepHeterogen/ballerDepHeterogenScripts/Imaging/matched/fc_communities_three_scans/fc_and_mdmr_functions_NEW_NBACK_27parcels.R')
args <- commandArgs(trailingOnly=TRUE)
cat(args,'\n')
timeseries <- as.character(args[1])
write_new_ts_file_with_13_rois(timeseries)
